/**
 * User Role Enum
 */
export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

/**
 * User Entity Interface
 */
export interface IUser {
  id: string;
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  role: Role;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * User Entity Class
 */
export class User {
  constructor(
    public readonly id: string,
    public email: string,
    public password: string,
    public firstName: string,
    public lastName: string,
    public role: Role = Role.USER,
    public isActive: boolean = true,
    public readonly createdAt: Date = new Date(),
    public updatedAt: Date = new Date()
  ) {}

  /**
   * Get user's full name
   */
  getFullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }

  /**
   * Check if user is admin
   */
  isAdmin(): boolean {
    return this.role === Role.ADMIN;
  }

  /**
   * Check if user is active
   */
  isUserActive(): boolean {
    return this.isActive;
  }

  /**
   * Update user information
   */
  updateInfo(updates: Partial<Pick<User, 'firstName' | 'lastName' | 'email'>>): void {
    if (updates.firstName) this.firstName = updates.firstName;
    if (updates.lastName) this.lastName = updates.lastName;
    if (updates.email) this.email = updates.email;
    this.updatedAt = new Date();
  }

  /**
   * Update password
   */
  updatePassword(newPassword: string): void {
    this.password = newPassword;
    this.updatedAt = new Date();
  }

  /**
   * Change user role
   */
  changeRole(newRole: Role): void {
    this.role = newRole;
    this.updatedAt = new Date();
  }

  /**
   * Activate user account
   */
  activate(): void {
    this.isActive = true;
    this.updatedAt = new Date();
  }

  /**
   * Deactivate user account
   */
  deactivate(): void {
    this.isActive = false;
    this.updatedAt = new Date();
  }

  /**
   * Convert to plain object (without sensitive data)
   */
  toPublicObject(): Omit<IUser, 'password'> {
    return {
      id: this.id,
      email: this.email,
      firstName: this.firstName,
      lastName: this.lastName,
      role: this.role,
      isActive: this.isActive,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }

  /**
   * Create a User instance from a plain object
   */
  static fromObject(data: IUser): User {
    return new User(
      data.id,
      data.email,
      data.password,
      data.firstName,
      data.lastName,
      data.role,
      data.isActive,
      data.createdAt,
      data.updatedAt
    );
  }

  /**
   * Create a new User instance
   */
  static create(
    email: string,
    password: string,
    firstName: string,
    lastName: string,
    role: Role = Role.USER
  ): User {
    return new User(
      '', // ID will be generated by database
      email,
      password,
      firstName,
      lastName,
      role,
      true
    );
  }
}

/**
 * Refresh Token Entity Interface
 */
export interface IRefreshToken {
  id: string;
  token: string;
  userId: string;
  expiresAt: Date;
  createdAt: Date;
}

/**
 * Refresh Token Entity Class
 */
export class RefreshToken {
  constructor(
    public readonly id: string,
    public token: string,
    public userId: string,
    public expiresAt: Date,
    public readonly createdAt: Date = new Date()
  ) {}

  /**
   * Check if token is expired
   */
  isExpired(): boolean {
    return new Date() > this.expiresAt;
  }

  /**
   * Get time until expiration in milliseconds
   */
  getTimeUntilExpiration(): number {
    return this.expiresAt.getTime() - Date.now();
  }

  /**
   * Create a RefreshToken instance from a plain object
   */
  static fromObject(data: IRefreshToken): RefreshToken {
    return new RefreshToken(
      data.id,
      data.token,
      data.userId,
      data.expiresAt,
      data.createdAt
    );
  }

  /**
   * Create a new RefreshToken instance
   */
  static create(token: string, userId: string, expiresAt: Date): RefreshToken {
    return new RefreshToken(
      '', // ID will be generated by database
      token,
      userId,
      expiresAt
    );
  }
}

/**
 * User Profile Interface (public data)
 */
export interface IUserProfile {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  fullName: string;
  role: Role;
  isActive: boolean;
  createdAt: Date;
}

/**
 * User Session Interface
 */
export interface IUserSession {
  userId: string;
  email: string;
  role: Role;
  accessToken: string;
  refreshToken: string;
  accessTokenExpiresAt: Date;
  refreshTokenExpiresAt: Date;
}
