#!/bin/bash
# Setup Script for E-commerce Platform Observability Stack
# This script initializes and configures the complete observability infrastructure

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.observability.yml"
ENV_FILE="$PROJECT_DIR/.env"

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        log_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    
    # Check if Docker is running
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running. Please start Docker first."
        exit 1
    fi
    
    log_success "Prerequisites check passed"
}

# Create environment file
create_env_file() {
    log_info "Creating environment file..."
    
    if [ -f "$ENV_FILE" ]; then
        log_warning ".env file already exists. Skipping creation."
        return
    fi
    
    cat > "$ENV_FILE" << 'EOF'
# Observability Stack Environment Configuration
# Generated by setup.sh

# ==========================================
# Grafana Configuration
# ==========================================
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=changeme-strong-password
GRAFANA_SECRET_KEY=your-secret-key-here
GRAFANA_ROOT_URL=http://localhost:3000

# ==========================================
# Database Credentials
# ==========================================
GRAFANA_DB_PASSWORD=grafana-db-password
REDIS_PASSWORD=redis-password

# ==========================================
# Notification Configuration
# ==========================================
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/WEBHOOK/URL
PAGERDUTY_KEY=your-pagerduty-integration-key
EMAIL_PASSWORD=your-email-password

# ==========================================
# SMTP Configuration (for Grafana alerts)
# ==========================================
GF_SMTP_ENABLED=false
GF_SMTP_HOST=smtp.gmail.com:587
GF_SMTP_USER=alerts@ecommerce-platform.com
GF_SMTP_PASSWORD=your-smtp-password
GF_SMTP_FROM_ADDRESS=alerts@ecommerce-platform.com

# ==========================================
# Elasticsearch Configuration (for Jaeger)
# ==========================================
ES_USERNAME=
ES_PASSWORD=

EOF
    
    log_success "Environment file created at $ENV_FILE"
    log_warning "Please update the .env file with your actual credentials before starting the stack"
}

# Create required directories
create_directories() {
    log_info "Creating required directories..."
    
    mkdir -p "$PROJECT_DIR/data/prometheus"
    mkdir -p "$PROJECT_DIR/data/grafana"
    mkdir -p "$PROJECT_DIR/data/loki"
    mkdir -p "$PROJECT_DIR/data/jaeger"
    mkdir -p "$PROJECT_DIR/data/alertmanager"
    mkdir -p "$PROJECT_DIR/data/elasticsearch"
    
    log_success "Directories created"
}

# Set permissions
set_permissions() {
    log_info "Setting permissions..."
    
    # Set ownership for Grafana (UID 472)
    if id -u 472 &>/dev/null; then
        chown -R 472:472 "$PROJECT_DIR/data/grafana" 2>/dev/null || true
    fi
    
    # Make scripts executable
    chmod +x "$PROJECT_DIR/health-check/health-check.sh" 2>/dev/null || true
    
    log_success "Permissions set"
}

# Pull images
pull_images() {
    log_info "Pulling Docker images..."
    
    cd "$PROJECT_DIR"
    docker-compose -f "$COMPOSE_FILE" pull
    
    log_success "Images pulled successfully"
}

# Start services
start_services() {
    log_info "Starting observability services..."
    
    cd "$PROJECT_DIR"
    docker-compose -f "$COMPOSE_FILE" up -d
    
    log_success "Services started"
}

# Wait for services to be ready
wait_for_services() {
    log_info "Waiting for services to be ready..."
    
    local services=("prometheus:9090" "grafana:3000" "loki:3100" "jaeger:16686" "alertmanager:9093")
    local max_attempts=30
    local attempt=1
    
    for service in "${services[@]}"; do
        IFS=':' read -r name port <<< "$service"
        attempt=1
        
        while [ $attempt -le $max_attempts ]; do
            if curl -s "http://localhost:$port" > /dev/null 2>&1; then
                log_success "$name is ready"
                break
            fi
            
            log_info "Waiting for $name... (attempt $attempt/$max_attempts)"
            sleep 5
            ((attempt++))
        done
        
        if [ $attempt -gt $max_attempts ]; then
            log_error "$name failed to start"
        fi
    done
}

# Verify installation
verify_installation() {
    log_info "Verifying installation..."
    
    echo ""
    echo "=========================================="
    echo "  Observability Stack URLs"
    echo "=========================================="
    echo ""
    echo -e "  ${GREEN}Prometheus:${NC}      http://localhost:9090"
    echo -e "  ${GREEN}Grafana:${NC}         http://localhost:3000"
    echo -e "  ${GREEN}Loki:${NC}            http://localhost:3100"
    echo -e "  ${GREEN}Jaeger:${NC}          http://localhost:16686"
    echo -e "  ${GREEN}Alertmanager:${NC}    http://localhost:9093"
    echo ""
    echo "=========================================="
    echo ""
    
    # Run health check
    if [ -f "$PROJECT_DIR/health-check/health-check.sh" ]; then
        bash "$PROJECT_DIR/health-check/health-check.sh"
    fi
}

# Show usage
show_usage() {
    echo "Usage: $0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  setup       - Full setup (default)"
    echo "  start       - Start all services"
    echo "  stop        - Stop all services"
    echo "  restart     - Restart all services"
    echo "  status      - Check service status"
    echo "  logs        - Show service logs"
    echo "  update      - Update images and restart"
    echo "  cleanup     - Remove all data and containers"
    echo "  help        - Show this help message"
    echo ""
}

# Start command
start_command() {
    log_info "Starting services..."
    cd "$PROJECT_DIR"
    docker-compose -f "$COMPOSE_FILE" up -d
    wait_for_services
    verify_installation
}

# Stop command
stop_command() {
    log_info "Stopping services..."
    cd "$PROJECT_DIR"
    docker-compose -f "$COMPOSE_FILE" down
    log_success "Services stopped"
}

# Restart command
restart_command() {
    stop_command
    start_command
}

# Status command
status_command() {
    cd "$PROJECT_DIR"
    docker-compose -f "$COMPOSE_FILE" ps
    echo ""
    if [ -f "$PROJECT_DIR/health-check/health-check.sh" ]; then
        bash "$PROJECT_DIR/health-check/health-check.sh"
    fi
}

# Logs command
logs_command() {
    cd "$PROJECT_DIR"
    if [ -z "$1" ]; then
        docker-compose -f "$COMPOSE_FILE" logs -f
    else
        docker-compose -f "$COMPOSE_FILE" logs -f "$1"
    fi
}

# Update command
update_command() {
    log_info "Updating observability stack..."
    cd "$PROJECT_DIR"
    docker-compose -f "$COMPOSE_FILE" pull
    docker-compose -f "$COMPOSE_FILE" up -d
    log_success "Update completed"
}

# Cleanup command
cleanup_command() {
    log_warning "This will remove all containers and data!"
    read -p "Are you sure? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cd "$PROJECT_DIR"
        docker-compose -f "$COMPOSE_FILE" down -v
        rm -rf "$PROJECT_DIR/data"
        log_success "Cleanup completed"
    else
        log_info "Cleanup cancelled"
    fi
}

# Main setup
setup() {
    echo "========================================"
    echo "  E-commerce Platform Observability"
    echo "  Setup Script"
    echo "========================================"
    echo ""
    
    check_prerequisites
    create_env_file
    create_directories
    set_permissions
    pull_images
    start_services
    wait_for_services
    verify_installation
    
    echo ""
    log_success "Setup completed successfully!"
    echo ""
    echo "Next steps:"
    echo "  1. Update the .env file with your credentials"
    echo "  2. Access Grafana at http://localhost:3000"
    echo "  3. Default login: admin / changeme-strong-password"
    echo "  4. Review and customize alert rules in prometheus/alert_rules.yml"
    echo ""
}

# Main
main() {
    case "${1:-setup}" in
        setup)
            setup
            ;;
        start)
            start_command
            ;;
        stop)
            stop_command
            ;;
        restart)
            restart_command
            ;;
        status)
            status_command
            ;;
        logs)
            logs_command "$2"
            ;;
        update)
            update_command
            ;;
        cleanup)
            cleanup_command
            ;;
        help|--help|-h)
            show_usage
            ;;
        *)
            log_error "Unknown command: $1"
            show_usage
            exit 1
            ;;
    esac
}

main "$@"
